const express = require('express')
const shop = require('./shops')
const catagory = require('./catagories')
const market = require('./markets')
const product = require('./products')
const blog = require('./blogs')
const cart = require('./carts')
const cartStatus = require('./cartStatuses')
const favorite = require('./favorites')
const order = require('./orders')
const user = require('./users')
const orderStatus = require('./orderStatuses')
const payment = require('./payments')
const account = require('./accounts')

const routes = express.Router()

routes.use(shop)
routes.use(catagory)
routes.use(market)
routes.use(product)
routes.use(blog)
routes.use(cart)
routes.use(cartStatus)
routes.use(favorite)
routes.use(order)
routes.use(user)
routes.use(account)
routes.use(orderStatus)
routes.use(payment)

module.exports = routes
